_format_version: "3.0"
services:
- connect_timeout: 60000
  enabled: true
  host: mock.insomnia.rest
  name: mockbin_service
  path: /request
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: mockbin_route
    path_handling: v0
    paths:
    - /mocks
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
